### ISSUE TITLE
Mesh file .g[?] primitive format

### ISSUE THREAD

**Issue by erichVK5** [Polymaker/ldd-modder#1]
Are you able to point me in the direction of any details of the .g[1,2,3,4] primitive object file format? I'd like to write some code to convert the meshes to other formats.

Cheers.

**Comment by Polymaker** [comment]
Yes of course. I've already made a file that maps the structure that I've understood so far: https://github.com/Polymaker/ldd-modder/blob/develop/Documentation/G%20(mesh)%20file%20format.txt

It is not very detailed so if you need more explanation feel free to ask,
If you only need the 3D mesh data it will be pretty simple. Most of the stuff I still don't understand are things related to shading and culling used in LDD.

**Comment by Polymaker** [comment]
Also you can look at this file to see how I read the 3D mesh data :
https://github.com/Polymaker/ldd-modder/blob/develop/LDDModder/Library.Display/Models/LddMeshLoader.cs

**Comment by erichVK5** [comment]
Thanks, that should be enough to get me going!!
