### ISSUE TITLE
[Feature Request]: Stud Connection Editor - Copy/Paste

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#10]
When you select an item in the grid, you can't copy and paste via ctrl-C/ctrl-V. You have to double-click one cell at a time and edit manually. Ideally I'd like to select a whole row or column and enter in a number and have it populate to all the cells. 

It would even be nice if this worked like an excel spreadsheet, and maybe have different cell background colours for different (known) types, such as RED for walls, BLUE for studs, GREEN for anti-studs, etc... That way you can see at a glance if your grid matches the part.

**Comment by Polymaker** [comment]
Copy-pasting is another thing that I've done recently and it will be in the next release.

Color coding is a great idea. I will work on that after the next release.

I really appreciate your comments! 
One thing that slows me down is that I have too many ideas and most are either too vague or too complex. 
So having requests and suggestions like yours actually help me priorities things and refine some of my ideas.

**Comment by zweifuss** [comment]
No problem, glad to suggest ideas... I've been using the software for the past month or so and I always thought 'maybe this might be a good thing' or 'I don't like how it does this' and just now have thought of putting it in this list. Hopefully I don't bombard you with too much stuff...
