### ISSUE TITLE
[Feature Request] - Deleting items on the main screen

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#11]
Sometimes I separate a mesh and I want to delete multiple items. Or I want to delete multiple collisions. When I try to shift-select (or ctrl-select) items, or even select a single item, and press DEL (in the main window), nothing happens. The only way to delete multiple items is to do it in the project tree. It would be nice to do it from the main window. It would be nice even to have a right-click context-sensitive menu in the main screen.

The workaround right now is the expand all the models tree items (hitting plus on every single item), select items in the main window, go back to the Navigation menu, right-click and press DEL there, then it works.

**Comment by Polymaker** [comment]
This is definitely in my to-do list. I've just been avoiding doing it because I also have to implement a delete confirmation system for certain elements (like stud connection that can be referenced by culling model).

I will try my best to have it ready for the next release.

**Comment by zweifuss** [comment]
Thank you! It really is no hurry, it's already a very functional software, even in Alpha stage...

**Comment by Polymaker** [comment]
Hi!
I just wanted to let you know that I finished to add this functionality.
I also added shortcuts to hide/unhide elements like in Blender.
And while I was working with shortcuts I fixed the issue with the numpad.

I'm only waiting to finish the connections editor before making a new release.
It should be ready around next week.

**Comment by zweifuss** [comment]
That's great news! Looking forward to it.
