### ISSUE TITLE
Numpad number inputs

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#13]
When I use the numpad to input coordinates into the location/rotation boxes, the number pressed affects the main viewing window (for example I want to put '1' into the X location, but instead of putting the number in there it rotates my model to view it from the front).

**Comment by Polymaker** [comment]
I remember fixing this issue but it is possible that it only applies when the focus is in the bottom panels.
Maybe it's just because it was done after the previous release.
Anyway I know the issue and it will be fixed in the next release. 🙂
