### ISSUE TITLE
Adding Connections - Cylindrical

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#15]
When I add a cylindrical connection, it defaults to '5 - Cross Axle', and I am not able to change the type. If I pick a new one in the sub-type pull-down menu, it doesn't change it. If I click away from it and come back to it, it defaults back to '5 - Cross Axle'. The only way to change it is to edit the XML file manually. This also goes for the connection parameters for studs as well, I can't change the sub-type within Brick Studio, only if I edit the XML file manually.

**Comment by Polymaker** [comment]
It is not really a bug... It is just that I never finished this section and it only loads the current value in the combobox.
I re-made this section from scratch today and it is now fully functional. I will make anew release soon.

**Comment by zweifuss** [comment]
Thank you! I know this is still an Alpha release, so maybe I'll hold off on the 'bug' reports until it goes into Beta stage. I don't want to wear you out with too much stuff at this point!
