### ISSUE TITLE
[Feature Request] LDRAW import

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#16]
It would be nice to have a straight LDRAW (.DAT file) import option. That way the users going through Blender or other programs don't have to worry about what checkboxes to tick off when importing/exporting. I feel there is something lost in translation with all the imports and exports.

**Comment by Polymaker** [comment]
I don't see how this would be helpful because models from LDRAW always requires manual editing.
The geometry is not good enough to be imported straight into LDD.

Anyway I haven't found any LDRAW importer for C# so I would have to develop one from scratch so it does not worth it.

**Comment by zweifuss** [comment]
Understandable! Thanks for the explanation.
