### ISSUE TITLE
[Feature Request] XML extra info

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#18]
When I am taking a brick from the LDRAW library and converting it into LDD, I like to credit the author from the LDRAW info page for that part. Only thing is, when I use Brick Studio and 'generate LDD files', it removes all this extra information from the XML file. I'd like there to be a special section in maybe "Part Properties' where I can put this information and have it stay there without me having to edit the XML file manually every time before I submit the file to the community.

**Comment by Polymaker** [comment]
This is definitively something I will do in the near future.
Also I learnt from the forum that some brick creators put their names in the primitive XML and this is also lost.

**Comment by Polymaker** [comment]
This feature was implemented in the latest release.
