### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by JOJOyh** [Polymaker/ldd-modder#19]
how to set the 3D Model size from 3D SoftWare.
it's too big or too small after i import a 3D Model

**Comment by Polymaker** [comment]
While my application has some features to edit 3D models, **it is not a 3D modeling software**.
You need to adjust the model in a 3D modeling software (like blender) beforehand.

My best advise is to open an existing part in Brick Studio and export the 3D model, then open the model in blender to find out what is the correct size.

**Comment by JOJOyh** [comment]
thanks a lot
