### ISSUE TITLE
V0.4 Crashes computer, V0.3 does not

### ISSUE THREAD

**Issue by finnrobinanders** [Polymaker/ldd-modder#22]
When attempting to run V0.4, my computer freezes and responds to nothing. Then, after about 20 seconds, the screen goes off, and I have to press the off button to log out, and then I log in again. Once logged in, LDD Modder is still open but I can close it through task manager.

V0.3 does not do this and works fine.

I am running Windows 10 on a 2019 Macbook Pro, through Bootcamp.

**Comment by Polymaker** [comment]
It took me a while to figure out what could be causing this issue and I think I found the culprit.
The fix will be in the next release.

**Comment by finnrobinanders** [comment]
Awesome thanks for working things out!

**Comment by Polymaker** [comment]
I just wanted to let you know that I did not forget you!
The fix for your issue is mixed with new features I've started and I did not have much spare time to finish them.
I will take some time during my winter holidays to get it ready for release.

**Comment by Polymaker** [comment]
This issue should be resolved in the latest release.

**Comment by finnrobinanders** [comment]
Thanks for fixing it. And no worries about forgetting me! We all have busy lives and I am in no hurry to make custom bricks.
I'll test it once the issue that has caused a 'do not download' note at the top of the latest version is resolved.

**Comment by Polymaker** [comment]
If all goes well the issue should be resolved tomorrow!
