### ISSUE TITLE
v1.0.6.1 keeps giving errors when trying to create LDD files

### ISSUE THREAD

**Issue by stephan3321** [Polymaker/ldd-modder#29]
Brick Studio v1.0.6.1 keeps giving errors when trying to generate LDD files:

> "An error occured." With in the Validation section "UNHANDLED_EXCEPTION".

When saving the file as project, another error shows when trying to re-open that file:

> System.NullReferenceException: The object reference is not set to an instance of an object.
   bij LDDModder.BrickEditor.Rendering.SurfaceMeshBuffer.AddMeshGeometry(ModelMeshReference modelMesh, List\`1 indexList, List\`1 vertexList)
   bij LDDModder.BrickEditor.Rendering.SurfaceMeshBuffer.RebuildPartModels()
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.AddPartSurfaceModel(PartSurface surface)
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.RebuildSurfaceModels()
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.OnProjectLoaded(PartProject project)
   bij LDDModder.BrickEditor.UI.Panels.ProjectDocumentPanel.ProjectManager_ProjectChanged(Object sender, EventArgs e)
   bij System.EventHandler.Invoke(Object sender, EventArgs e)
   bij LDDModder.BrickEditor.ProjectHandling.ProjectManager.SetCurrentProject(PartProject project, String tempPath)
   bij LDDModder.BrickEditor.UI.Windows.BrickEditorWindow.LoadPartProject(PartProject project, String tempPath)
   bij LDDModder.BrickEditor.UI.Windows.BrickEditorWindow.OpenPartProjectFile(String projectFilePath)
   bij LDDModder.BrickEditor.UI.Windows.BrickEditorWindow.RecentFileMenuEntry_Click(Object sender, EventArgs e)

**Comment by Polymaker** [comment]
That is really strange.
If I understand correctly, you are opening a part directly from LDD (menu "Create from brick...).
Could you tell me which part ID it is? Also it could help me if you send me the *.xml and *.g from LDD in a zip (you can drag the zip in the comment)

Do you have the issue with any brick? Did you try opening a non-custom brick to see if you have the issue?

Also, could you send me the "lpp" file that you saved. I have an idea of what might cause the issue.

**Comment by stephan3321** [comment]
Yes, I load an (existing) part from LDD ("Create from brick"). Then I change something (collision, connection) and try to "Create LDD files" and the error occurs.

It happens with all parts, original, new ones that I wanted to update, and completely never-been-in-LDD-before parts. It usually takes three or four times reloading the LDD part before the files can be created.

In the *.zip file are 3 *.lpp files which all have the issue, 1 *.xml file and its 3 *.g files.


[Zip file.zip](https://github.com/Polymaker/ldd-modder/files/5804864/Zip.file.zip)

**Comment by Polymaker** [comment]
Now that I think of it, this problem looks exactly like the one there was with version 1.0.6.0.
Are you sure you have downloaded the correct one? 
I've found the issue with version 1.0.6.0 about a day after I released it and then shortly after I released v1.0.6.1. 

To check the version you have you can open the menu "? -> About".
If you really are on version 1.0.6.1 then there is something weird going on.

In the meantime, DO NOT override existing "*.lpp" files because the models contained inside are lost when you save.
(you can open the "lpp" files you sent me in notepad and you will see that the "Meshes" element is empty and only has comments)

**Comment by stephan3321** [comment]
I have to check that. I downloaded the version 1.0.6.1 a few days after I saw your message about the faulty v1.0.6.0. So, that shouldn't have been a problem. I even re-downloaded and re-installed it yesterday due to the error. I use the 64-bit *.msi file.

**Comment by Polymaker** [comment]
This is more and more strange. This problem should not be "system specific", so the same problem should also happen to me but it does not...
Could you try one more thing for me? 
* Start Brick Studio and open a part from LDD. Then while it is still open and not saved, open Windows explorer and navigate to:
"C:\Users\ **your user** \AppData\Roaming\LDDModder\BrickEditor"
* You should see a file named "**settings.json**". Open  it in notepad. You should see something like that:
`"file.opened": [
    {
      "PartID": 1026,
      "PartName": "Sheet Plastic 10 x 17 Trapezoidal",
      "ProjectFile": null,
      "TemporaryPath": "C:\\Users\\james\\AppData\\Local\\Temp\\563a3c5e80f44cbc\\project.xml"
    }
  ],`
* Then go at the location of **TemporaryPath** and send me the "**project.xml**" file.

**Comment by Polymaker** [comment]
I think I found one thing that can reproduce your problem!
If I understand correctly, you said that you can sometime export the parts.
By any chance, when you encounter the issue, has the file been open in Brick Studio for more than 1 minute?
I found a bug with the auto-save feature that occurs every minutes.

**Comment by stephan3321** [comment]
I will follow your instructions for the project.xml file.

Yes, because when quickly exporting files it doesn't happen. When editting collisions (which indeed takes over +1 minute), the problem occurs.

**Comment by Polymaker** [comment]
You can forget about sending me the "project.xml" file then. It seems I found the issue.
I will fix it but in the meantime you can change the auto-save interval in the settings window. You need to restart Brick Studio after.

**Comment by Polymaker** [comment]
Hi Stephan!

I've just released v1.0.6.2 that should fix the issue!

Let me know if that works for you!

**Comment by stephan3321** [comment]
Unfortunatelly it doesn't work for original parts nor new parts. When trying to load a part from LDD, it gives me another error:

`System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij LDDModder.BrickEditor.Rendering.SurfaceMeshBuffer.AddMeshGeometry(ModelMeshReference modelMesh, List`1 indexList, List`1 vertexList)
   bij LDDModder.BrickEditor.Rendering.SurfaceMeshBuffer.RebuildPartModels()
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.AddPartSurfaceModel(PartSurface surface)
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.RebuildSurfaceModels()
   bij LDDModder.BrickEditor.UI.Panels.ViewportPanel.OnProjectLoaded(PartProject project)
   bij LDDModder.BrickEditor.UI.Panels.ProjectDocumentPanel.ProjectManager_ProjectChanged(Object sender, EventArgs e)
   bij System.EventHandler.Invoke(Object sender, EventArgs e)
   bij LDDModder.BrickEditor.ProjectHandling.ProjectManager.SetCurrentProject(PartProject project, String tempPath)
   bij LDDModder.BrickEditor.UI.Windows.BrickEditorWindow.LoadPartProject(PartProject project, String tempPath)
   bij LDDModder.BrickEditor.UI.Windows.BrickEditorWindow.LoadNewPartProject(PartProject project)`

**Comment by Polymaker** [comment]
Oops. My bad, I did not re-test importing from LDD before releasing.
I fixed it *again* and updated the setup in the release.

**Important note:** Since I included this last fix in the same version, you will need to uninstall v1.0.6.2 before installing it again.

**Comment by stephan3321** [comment]
So far no problems. Everything seems to work just fine.
