### ISSUE TITLE
subMaterialRedirectLookupTable in Primitive 

### ISSUE THREAD

**Issue by sttng** [Polymaker/ldd-modder#4]
Hi there. Sorry to bother again. Do you ever found out the meaning of number of the subMaterialRedirectLookupTable entry in primitive xml files ?

**Comment by Polymaker** [comment]
No problem! From what I understand, it is only used to synchronize the color of multi surfaces part.
Let's say we have XXXX.g, XXXX.g1 and XXXX.g2. If the subMaterialRedirectLookupTable is "0,1,0", then when applying the paint bucket on the main surface (mesh from the XXXX.g file) the third surface (XXXX.g2) will have the same color applied.
I think it's main purpose is to prevent changing a surface color when you only want to allow decals.
That is why you often see "0,0".

**Comment by Polymaker** [comment]
By the way, I think we should have a chat somewhere more appropriate if you're interested.
I have many info about LDD that are only resting in my head and I don't have time to document it all. 
Things like how to edit the main palette (LDD theme), how to make suspension parts works, how to edit and add translations, some undisclosed flags you can set in the preferences.ini and many more things.
