### ISSUE TITLE
I can't open it in win10

### ISSUE THREAD

**Issue by ish-kafel** [Polymaker/ldd-modder#6]
I install this software but can't open it
system: win10 1709

**Comment by Polymaker** [comment]
is there any error message?
Also by any chance, is your LDD installed in a folder other than "Program Files"?
In the current release there is a bug if it is installed elsewhere.

I will make a new release soon (maybe today).

**Comment by ish-kafel** [comment]
Yes, I installed in D:/LDD
That would be appreciated

**Comment by Polymaker** [comment]
Ok. I'm currently preparing the next release that fixes this issue It should be ready in a few minutes.
I'll let you know when it is ready.

**Comment by Polymaker** [comment]
Here you can download the [latest version here](https://github.com/Polymaker/ldd-modder/releases/tag/v0.3-alpha)

**Comment by ish-kafel** [comment]
Great! and thank you for your efforts to add parts to LDD😃

**Comment by Polymaker** [comment]
Let me know if the latest version fixes your issue!

**Comment by ish-kafel** [comment]
The issue was fixed!
