### ISSUE TITLE
Can't duplicate connections

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#8]
When I right-click on any connection and pick 'duplicate', there is no duplicate made. Duplicate only seems to work for collision boxes. This is for AlphaRelease v0.3

**Comment by Polymaker** [comment]
Yes you are correct. The option is (almost?) always present but in the current release it only works for collisions.

I recently enabled duplicating connections and it will be in the next release.

It will also include flexible part editing 😀
