### ISSUE TITLE
Stud Connection Editor - increasing the grid

### ISSUE THREAD

**Issue by zweifuss** [Polymaker/ldd-modder#9]
When I put two new values in for increasing a grid, for example, 1:1 I want to go to 2:2, I put 2 in each field, and hit apply, only the second field is applied. The second field still stays at 1. I have to change width, hit apply, then pick the height, and hit apply again. Related issue, the new fields added are 0:0:0, which is an illegal type. Would it be possible to make these 29:0:0 as defaults?

**Comment by Polymaker** [comment]
I don't remember getting this problem but I will look.

And thank you for the idea to put 29:0:0 by default, it will prevent LDD from crashing 🤣
